/**
 * Analytics service
 *
 * Performance numbers come from real posts + post_metrics: see getPosts()
 * in campaign.service.ts and the pure calculations in lib/analytics.ts.
 *
 * What's left here is still mock: the assistant's audience learnings
 * (to be generated by the AI layer from lib/analytics findings).
 */

import { mockAudienceLearnings } from "@/data/mock-analytics";

export async function getAudienceLearnings(businessId: string): Promise<string[]> {
  void businessId;
  return mockAudienceLearnings;
}
