/**
 * Recommendation service
 *
 * Recommendations are generated by the AI (or the guided engine) from the
 * business's own data — see generateRecommendations() in lib/ai/ai.service —
 * and stored in ai_recommendations (migration 012), refreshed weekly or on
 * demand. Owners can read and dismiss; writes use the secret key.
 */

import type { AIRecommendation, CampaignGoal, RecommendationSource, RecommendationType } from "@/types";
import type { AiRecommendationRow, RecommendationDetails } from "@/lib/supabase/database.types";
import { createAdminClient, createServerClient } from "@/lib/supabase/server";

/** "Recommended for this week": regenerate when the newest is older than this. */
export const RECOMMENDATION_MAX_AGE_DAYS = 7;

function toRecommendation(row: AiRecommendationRow): AIRecommendation {
  const details: RecommendationDetails = row.details ?? {};
  return {
    id: row.id,
    businessId: row.business_id,
    type: row.type,
    title: row.title,
    explanation: row.explanation,
    confidence: row.confidence === null ? undefined : Number(row.confidence),
    source: row.source,
    actionLabel: row.action_label ?? undefined,
    actionGoal: row.action_goal ?? undefined,
    productId: row.product_id ?? undefined,
    chips: details.chips ?? [],
    promotion: details.promotion,
    generatedBy: row.generated_by ?? "guided",
    createdAt: row.created_at,
  };
}

/** Current (not dismissed) recommendations, best first. */
export async function getRecommendations(businessId: string): Promise<AIRecommendation[]> {
  const supabase = await createServerClient();
  const { data, error } = await supabase
    .from("ai_recommendations")
    .select("*")
    .eq("business_id", businessId)
    .is("dismissed_at", null)
    .order("created_at", { ascending: false })
    .order("confidence", { ascending: false, nullsFirst: false })
    .limit(6);
  if (error) {
    // e.g. migration 012 not applied yet — show the rules-based fallback.
    console.error("Could not load recommendations", error.message);
    return [];
  }
  return data.map(toRecommendation);
}

/** True when there are no current recommendations or they're over a week old. */
export function recommendationsAreStale(recommendations: AIRecommendation[]): boolean {
  if (recommendations.length === 0) return true;
  const newest = Math.max(...recommendations.map((r) => new Date(r.createdAt).getTime()));
  return Date.now() - newest > RECOMMENDATION_MAX_AGE_DAYS * 86_400_000;
}

/** Hides a recommendation (RLS: owners may only set dismissed_at). */
export async function dismissRecommendation(id: string, businessId: string): Promise<void> {
  const supabase = await createServerClient();
  const { error } = await supabase
    .from("ai_recommendations")
    .update({ dismissed_at: new Date().toISOString() })
    .eq("id", id)
    .eq("business_id", businessId);
  if (error) throw error;
}

export interface NewRecommendation {
  type: RecommendationType;
  title: string;
  explanation: string;
  confidence?: number;
  source: RecommendationSource;
  actionLabel?: string;
  actionGoal?: CampaignGoal;
  productId?: string;
  chips: string[];
  promotion?: string;
  generatedBy: "ai" | "guided";
}

/**
 * Replaces the business's current recommendations with a new set: the old
 * ones are marked dismissed (kept as history), the new ones inserted.
 * Server-only — uses the secret key, because owners can't insert.
 */
export async function replaceRecommendations(
  businessId: string,
  recommendations: NewRecommendation[]
): Promise<void> {
  if (recommendations.length === 0) return;
  const admin = createAdminClient();

  const { error: supersedeError } = await admin
    .from("ai_recommendations")
    .update({ dismissed_at: new Date().toISOString() })
    .eq("business_id", businessId)
    .is("dismissed_at", null);
  if (supersedeError) throw supersedeError;

  const { error } = await admin.from("ai_recommendations").insert(
    recommendations.map((r) => ({
      business_id: businessId,
      type: r.type,
      title: r.title,
      explanation: r.explanation,
      confidence: r.confidence ?? null,
      source: r.source,
      action_label: r.actionLabel ?? null,
      action_goal: r.actionGoal ?? null,
      product_id: r.productId ?? null,
      details: { chips: r.chips, ...(r.promotion && { promotion: r.promotion }) },
      generated_by: r.generatedBy,
    }))
  );
  if (error) throw error;
}
