-- ============================================================
-- Migration 012 — AI recommendations
--
-- Recommendations ("Recommended for this week" on Home, "Ideas to
-- put into action" on the assistant page) are generated by the AI
-- (or the guided engine) from the business's own data and stored
-- here, refreshed weekly or on demand.
--
--   product_id    — the product the recommendation is about, so
--                   "Create campaign" can pre-select it
--   details       — suggestion specifics shown as chips:
--                   { platforms, weekday, time, promotion, chips[] }
--   generated_by  — 'ai' (language model) or 'guided' (rules)
--
-- Writes happen server-side with the secret key (owners can only
-- read and dismiss, per migration 004). Also added to realtime so
-- open tabs pick up fresh recommendations.
-- ============================================================

alter table ai_recommendations
  add column if not exists product_id   uuid references products (id) on delete set null,
  add column if not exists details      jsonb not null default '{}',
  add column if not exists generated_by text  not null default 'guided'
    check (generated_by in ('ai', 'guided'));

create index if not exists idx_ai_recommendations_product_id
  on ai_recommendations (product_id);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ai_recommendations'
  ) then
    alter publication supabase_realtime add table public.ai_recommendations;
  end if;
end;
$$;
